const firstName : string =  'Arm'
let y : number = 10
y = 20
let want_to_go_home : boolean = true

console.log (firstName)
console.log (want_to_go_home)
console.log (y)

=== // เท่ากับ
  === // ไม่เท่ากับ
  > // มากกว่า
  < // น้อยกว่า
  >= // มากว่าหรือเท่ากับ
  <= // น้อยกว่าหรือเท่ากับ

  const a: number = 27
const b : number =  16

console.log(a===b)
console.log(a>b)
console.log(a<=b)