console.log(1)                
console.log(2)
console.log(3)                
console.log(4)
console.log(5)                
console.log(6)
console.log(7)                
console.log(8)
console.log(9)                
console.log(10)

the for loop
the while loop
the do while loop

for1 (let i = 0 ; i <5 ; i++) {
    text += "the number is" + i + "br>" ;
}

for (let i = 0; i <=10 ; i++) {              //
    console.log(i)  
}