function helloWorld() {
    console.log("สวัสดี")
}

helloWorld() // ไม่มี input ไม่มี output

function helloName (name:string) {
    console.log(name) //ปริ้นออกมา เเต่ไม่ใช่outputนะจ้ะ
}

 (helloName('MAR')) //มีinput ไม่มี output
console.log helloName('MAR')

function getPi() {
    return 3.42
    
}

console.log(getPi()) // ไม่มีinput เเต่มีoutput


function st(fullname:string, surename: string) { //องค์ประกอบครบ 
    if (fullname === 'mix' && surename === 'zane') { // ||ตรงนี้เเปลว่า 'หรือ' เช่น มีเงินเเต่ไม่มีเหรียญเเสดงว่าเเทนได้ - && ตรงนี้เเปลว่า 'เเละ' เช่น มีเหรียญต้องมีเงิน,ขาดไม่ได้
        console.log('เริ่มสอน')
    }   else {
        console.log('ไม่สอน')
    }
}
st('mix','zane')

function br(fullname:string, surename: string) { // เเบบไม่สอน
    if (fullname === 'mix' && surename === 'zane') {
        console.log('เริ่มสอน')
    }   else {
        console.log('ไม่สอน')
    }
}
br('mix','boy')

ทดลองรับชื่อมา3คน



function st1(fullname:string, nickname:string, surename: string) {
    if (fullname === 'mix' && nickname === 'zane' && surename === 'forth' ) {
        console.log('พร้อมเรียน')
    }   else {
        console.log('ไม่พร้อมเรียน')
    }
}
st1('mix','zane','forth')

function st2(fullname:string, nickname:string, surename: string) {
    if (fullname === 'mix' && nickname === 'zane' && surename === 'forth' ) {
        console.log('พร้อมเรียน')
    }   else {
        console.log('ไม่พร้อมเรียน')
    }
}
st2('mix','zane','boy')

function st3(fullname:string, nickname:string, surename: string) {
    if (fullname === 'mix' && nickname === 'zane' || surename === 'forth' ) {
        console.log('พร้อมเรียน')
    }   else {
        console.log('ไม่พร้อมเรียน')
    }
}
st3('mix','zane','boy')

function st1(fullname:string, nickname:string, surename: string) { 
    if ((fullname === 'mix' || nickname === 'zane') && surename === 'forth' ) { //อันนี้เป็นเเบบ 1หรือ2 เเละ3 'คนสุดท้ายสำคัญสุด'
        console.log('พร้อมเรียน')                                                 // ! เปลี่ยน'เท็จ' 'เป็นจริง' เปลี่ยน'จริง' 'เป็นเท็จ'
    }   else {
        console.log('ไม่พร้อมเรียน')
    }
}
st1('mix','zane','forth')

function Man(Sex:string, height:number, weight: number) {
    if (Sex === 'Male' && (height  >= 170  || (weight >= 50  && weight <=110 ))) { // === คือ only หรือ เฉพาะ
        console.log('Random Card')
    }   else {
        console.log('Free dom')
    }
    
}
Man('Male',100,40)

if (Sex === 'Male' && (Height  > 170  || (Weight ===> 50  && Weight <=110 ))) //ลอง



    function Digtal(Old:number, Salary:number, Total : number) {
    if (Old >= 16 && (Salary  <=70000  && (Total  <=500000 ))) { 
        console.log('You Get 10000')
    }   else {
        console.log('You Are Not In Condition')
    }
    
}
Digtal(17,7000,8000)