
const data = [
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อ่างทอง",
        "new_case": 1,
        "total_case": 137,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 137,
        "new_death": 0,
        "total_death": 5,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "เชียงราย",
        "new_case": 0,
        "total_case": 192,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 192,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครราชสีมา",
        "new_case": 11,
        "total_case": 1926,
        "new_case_excludeabroad": 11,
        "total_case_excludeabroad": 1926,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ตราด",
        "new_case": 3,
        "total_case": 345,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 345,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สงขลา",
        "new_case": 2,
        "total_case": 1043,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 1043,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สตูล",
        "new_case": 0,
        "total_case": 12,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 12,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สิงห์บุรี",
        "new_case": 0,
        "total_case": 165,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 165,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นนทบุรี",
        "new_case": 7,
        "total_case": 1078,
        "new_case_excludeabroad": 7,
        "total_case_excludeabroad": 1078,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สุพรรณบุรี",
        "new_case": 2,
        "total_case": 334,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 334,
        "new_death": 0,
        "total_death": 13,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ราชบุรี",
        "new_case": 2,
        "total_case": 600,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 600,
        "new_death": 0,
        "total_death": 7,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ปทุมธานี",
        "new_case": 4,
        "total_case": 685,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 685,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "จันทบุรี",
        "new_case": 5,
        "total_case": 777,
        "new_case_excludeabroad": 5,
        "total_case_excludeabroad": 777,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ชัยนาท",
        "new_case": 0,
        "total_case": 46,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 46,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครสวรรค์",
        "new_case": 1,
        "total_case": 509,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 509,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สกลนคร",
        "new_case": 0,
        "total_case": 84,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 84,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "มหาสารคาม",
        "new_case": 0,
        "total_case": 41,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 41,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พัทลุง",
        "new_case": 0,
        "total_case": 159,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 159,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครพนม",
        "new_case": 1,
        "total_case": 149,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 149,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ลำพูน",
        "new_case": 2,
        "total_case": 124,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 124,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ลำปาง",
        "new_case": 4,
        "total_case": 182,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 182,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ฉะเชิงเทรา",
        "new_case": 1,
        "total_case": 271,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 271,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "เชียงใหม่",
        "new_case": 13,
        "total_case": 1034,
        "new_case_excludeabroad": 13,
        "total_case_excludeabroad": 1034,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อุบลราชธานี",
        "new_case": 5,
        "total_case": 813,
        "new_case_excludeabroad": 5,
        "total_case_excludeabroad": 813,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สุรินทร์",
        "new_case": 1,
        "total_case": 706,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 706,
        "new_death": 0,
        "total_death": 11,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "หนองบัวลำภู",
        "new_case": 0,
        "total_case": 80,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 80,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อุตรดิตถ์",
        "new_case": 0,
        "total_case": 217,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 217,
        "new_death": 0,
        "total_death": 5,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ชุมพร",
        "new_case": 6,
        "total_case": 1152,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 1152,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครนายก",
        "new_case": 0,
        "total_case": 21,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 21,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ไม่ระบุ",
        "new_case": 6,
        "total_case": 1681,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 1681,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "บุรีรัมย์",
        "new_case": 1,
        "total_case": 587,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 587,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ตรัง",
        "new_case": 1,
        "total_case": 360,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 360,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "น่าน",
        "new_case": 0,
        "total_case": 216,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 216,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "บึงกาฬ",
        "new_case": 0,
        "total_case": 58,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 58,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ลพบุรี",
        "new_case": 1,
        "total_case": 131,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 131,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ปราจีนบุรี",
        "new_case": 1,
        "total_case": 108,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 108,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สระบุรี",
        "new_case": 6,
        "total_case": 295,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 295,
        "new_death": 0,
        "total_death": 7,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ขอนแก่น",
        "new_case": 5,
        "total_case": 1238,
        "new_case_excludeabroad": 5,
        "total_case_excludeabroad": 1238,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "กำแพงเพชร",
        "new_case": 0,
        "total_case": 121,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 121,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "เพชรบูรณ์",
        "new_case": 3,
        "total_case": 422,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 422,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "แม่ฮ่องสอน",
        "new_case": 0,
        "total_case": 43,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 43,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ปัตตานี",
        "new_case": 0,
        "total_case": 29,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 29,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ประจวบคีรีขันธ์",
        "new_case": 1,
        "total_case": 244,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 244,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พระนครศรีอยุธยา",
        "new_case": 1,
        "total_case": 273,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 273,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ยโสธร",
        "new_case": 0,
        "total_case": 186,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 186,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นราธิวาส",
        "new_case": 0,
        "total_case": 67,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 67,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อุทัยธานี",
        "new_case": 1,
        "total_case": 159,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 159,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครศรีธรรมราช",
        "new_case": 0,
        "total_case": 676,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 676,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "กระบี่",
        "new_case": 0,
        "total_case": 194,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 194,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ทั้งประเทศ",
        "new_case": 287,
        "total_case": 39063,
        "new_case_excludeabroad": 287,
        "total_case_excludeabroad": 39063,
        "new_death": 3,
        "total_death": 207,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "กาฬสินธุ์",
        "new_case": 2,
        "total_case": 242,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 242,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พังงา",
        "new_case": 0,
        "total_case": 15,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 15,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อำนาจเจริญ",
        "new_case": 2,
        "total_case": 50,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 50,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สมุทรสงคราม",
        "new_case": 0,
        "total_case": 105,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 105,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สุราษฎร์ธานี",
        "new_case": 5,
        "total_case": 961,
        "new_case_excludeabroad": 5,
        "total_case_excludeabroad": 961,
        "new_death": 0,
        "total_death": 9,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "อุดรธานี",
        "new_case": 3,
        "total_case": 669,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 669,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ศรีสะเกษ",
        "new_case": 1,
        "total_case": 73,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 73,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ชัยภูมิ",
        "new_case": 1,
        "total_case": 170,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 170,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "เพชรบุรี",
        "new_case": 1,
        "total_case": 250,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 250,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สระแก้ว",
        "new_case": 0,
        "total_case": 417,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 417,
        "new_death": 0,
        "total_death": 11,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พะเยา",
        "new_case": 1,
        "total_case": 309,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 309,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "หนองคาย",
        "new_case": 4,
        "total_case": 423,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 423,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พิจิตร",
        "new_case": 3,
        "total_case": 253,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 253,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ภูเก็ต",
        "new_case": 2,
        "total_case": 799,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 799,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สุโขทัย",
        "new_case": 0,
        "total_case": 104,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 104,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สมุทรปราการ",
        "new_case": 4,
        "total_case": 715,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 715,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "แพร่",
        "new_case": 0,
        "total_case": 139,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 139,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "มุกดาหาร",
        "new_case": 0,
        "total_case": 87,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 87,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "เลย",
        "new_case": 0,
        "total_case": 483,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 483,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "นครปฐม",
        "new_case": 4,
        "total_case": 261,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 261,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "สมุทรสาคร",
        "new_case": 2,
        "total_case": 617,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 617,
        "new_death": 0,
        "total_death": 12,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ร้อยเอ็ด",
        "new_case": 3,
        "total_case": 494,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 494,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "กรุงเทพมหานคร",
        "new_case": 126,
        "total_case": 6904,
        "new_case_excludeabroad": 126,
        "total_case_excludeabroad": 6904,
        "new_death": 2,
        "total_death": 20,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "กาญจนบุรี",
        "new_case": 0,
        "total_case": 65,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 65,
        "new_death": 0,
        "total_death": 12,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ระนอง",
        "new_case": 0,
        "total_case": 4,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 4,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ระยอง",
        "new_case": 3,
        "total_case": 476,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 476,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "พิษณุโลก",
        "new_case": 1,
        "total_case": 492,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 492,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ตาก",
        "new_case": 0,
        "total_case": 342,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 342,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ชลบุรี",
        "new_case": 21,
        "total_case": 3067,
        "new_case_excludeabroad": 21,
        "total_case_excludeabroad": 3067,
        "new_death": 1,
        "total_death": 19,
        "update_date": "2024-09-30 09:21:12"
    },
    {
        "year": 2024,
        "weeknum": 38,
        "province": "ยะลา",
        "new_case": 0,
        "total_case": 107,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 107,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-30 09:21:12"
    },
];
const noNewCase = data.filter(function (element, index {
    return element.new_case === 0;
});

const onlyProvine = data.map(function (element, index) {
    return ({
        province: element.province,
        total: element.total_case,
    });
});

const noNewCaseOnlyProvine = data.filter(function (element, index {
    return element.new_case === 0;
}).map(function (element, index) {
    return ({
        province: element.province,
        total: element.total_case,
    });
}).map; 



