//โค้ดในชีวิตจริง

const me = {
    firstName: 'Mr.ChillTonTomSickLinkInMyMind' ,
    LastName : 'MaiChiNaMaiChiNa',
    age : 20,
    phoneNumber : 112,
    sex : 'male',
    addres : 'USA',
    city : 'newYorkCity',
    numBerCity : 10005,
    street :  'Beaver',
    numberStreet : 14,
    e-Mail : 'aadawdsadawdadadadwdad@gmail.com'
}

// ประวัติส่วนตัว

// ชื่อ : Achitphol
// นามสกุล : Lervilnareis
// อายุ : 20
//เบอร์โทร : 112
//เพศ : ชาย

